# Generated by Django 4.2.5 on 2024-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMerchantRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("provider", models.CharField(max_length=63, verbose_name="Provider")),
                ("header", models.TextField(verbose_name="Header")),
                ("body", models.TextField(verbose_name="Body")),
                ("method", models.CharField(max_length=32, verbose_name="Method")),
                ("response", models.TextField(blank=True, null=True)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "Payment Merchant Request Log",
                "verbose_name_plural": "Payment Merchant Request Logs",
            },
        ),
        migrations.CreateModel(
            name="Tilda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("project_id", models.IntegerField(verbose_name="Project ID")),
                ("group_id", models.IntegerField(verbose_name="Group ID")),
                ("cookie", models.TextField(verbose_name="Cookie")),
            ],
            options={
                "verbose_name": "Tilda",
                "verbose_name_plural": "Tildas",
            },
        ),
        migrations.DeleteModel(
            name="FrontendTranslation",
        ),
        migrations.DeleteModel(
            name="VersionHistory",
        ),
    ]
