# Generated by Django 4.2.5 on 2024-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_paymentmerchantrequestlog_tilda_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidTildaUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "user_email",
                    models.EmailField(max_length=254, verbose_name="User email"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="Course name"),
                ),
                ("tilda_toggled", models.BooleanField(verbose_name="Tilda toggled")),
                ("paid_at", models.DateTimeField(verbose_name="Paid at")),
            ],
            options={
                "verbose_name": "Paid Tilda User",
                "verbose_name_plural": "Paid Tilda Users",
            },
        ),
    ]
