# Generated by Django 4.2.5 on 2024-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_paidtildauser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tilda",
            options={"verbose_name": "Tilda", "verbose_name_plural": "Tilda"},
        ),
        migrations.AddField(
            model_name="paidtildauser",
            name="transaction_id",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Transaction ID"
            ),
            preserve_default=False,
        ),
    ]
