# Generated by Django 4.2.5 on 2024-06-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_tilda_options_paidtildauser_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paidtildauser",
            name="paid_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Paid at"),
        ),
    ]
