# Generated by Django 4.2.5 on 2024-06-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_paidtildauser_paid_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TildaRequestResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("request_body", models.TextField(verbose_name="Request")),
                ("request_headers", models.TextField(verbose_name="Headers")),
                ("response_headers", models.TextField(verbose_name="Response Headers")),
                (
                    "response_status_code",
                    models.IntegerField(verbose_name="Response Status Code"),
                ),
                ("response_body", models.TextField(verbose_name="Response")),
            ],
            options={
                "verbose_name": "Tilda Request Response Log",
                "verbose_name_plural": "Tilda Request Response Logs",
            },
        ),
    ]
