# Generated by Django 4.2.5 on 2024-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_tildarequestresponselog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tildarequestresponselog",
            old_name="response_status_code",
            new_name="status_code",
        ),
        migrations.AddField(
            model_name="tildarequestresponselog",
            name="type",
            field=models.CharField(default=1, max_length=255, verbose_name="Type"),
            preserve_default=False,
        ),
    ]
