# Generated by Django 4.2.5 on 2024-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0007_rename_response_status_code_tildarequestresponselog_status_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paidtildauser",
            name="tilda_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Tilda ID"),
        ),
    ]
